"""empty message

Revision ID: 39ece19f5a5d
Revises: 
Create Date: 2021-05-20 17:31:49.401404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39ece19f5a5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=4), nullable=True),
    sa.Column('password_hash', sa.String(length=86), nullable=True),
    sa.Column('password_salt', sa.String(length=10), nullable=True),
    sa.Column('last_directory_update', sa.String(length=10), nullable=True),
    sa.Column('user_image', sa.String(length=100), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=True),
    sa.Column('insert_user_id', sa.Integer(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('update_user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('ingate',
    sa.Column('slipid', sa.Integer(), nullable=False),
    sa.Column('sliptime', sa.DateTime(), nullable=True),
    sa.Column('vehicleno', sa.String(length=50), nullable=True),
    sa.Column('destination', sa.String(length=50), nullable=True),
    sa.Column('loading', sa.String(length=50), nullable=True),
    sa.Column('dlno', sa.String(length=50), nullable=True),
    sa.Column('transporter', sa.String(length=50), nullable=True),
    sa.Column('gate', sa.String(length=50), nullable=True),
    sa.Column('currentlogin', sa.String(length=50), nullable=True),
    sa.Column('driver', sa.String(length=50), nullable=True),
    sa.Column('controlno', sa.Integer(), nullable=True),
    sa.Column('driverid', sa.Integer(), nullable=True),
    sa.Column('tare', sa.Integer(), nullable=True),
    sa.Column('rfid', sa.Integer(), nullable=True),
    sa.Column('rfno', sa.String(length=50), nullable=True),
    sa.Column('locationid', sa.Integer(), nullable=True),
    sa.Column('transporterid', sa.Integer(), nullable=True),
    sa.Column('vehicleid', sa.Integer(), nullable=True),
    sa.Column('validslip', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('slipno', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('fueltime', sa.DateTime(), nullable=True),
    sa.Column('fuelperator', sa.String(length=50), nullable=True),
    sa.Column('wheeler', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('slipid')
    )
    op.create_table('locations',
    sa.Column('locationid', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('locationcode', sa.String(length=50), nullable=True),
    sa.Column('createdate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('locationid')
    )
    op.create_table('owner',
    sa.Column('ownerid', sa.Integer(), nullable=False),
    sa.Column('ownername', sa.String(length=50), nullable=True),
    sa.Column('address1', sa.String(length=50), nullable=True),
    sa.Column('address2', sa.String(length=50), nullable=True),
    sa.Column('pan', sa.String(length=50), nullable=True),
    sa.Column('aadhar', sa.String(length=50), nullable=True),
    sa.Column('mobile', sa.String(length=50), nullable=True),
    sa.Column('gst', sa.String(length=50), nullable=True),
    sa.Column('startdate', sa.DateTime(), nullable=True),
    sa.Column('enddate', sa.DateTime(), nullable=True),
    sa.Column('dlno', sa.String(length=50), nullable=True),
    sa.Column('isactive', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('statuschangedate', sa.DateTime(), nullable=True),
    sa.Column('stateid', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('pincode', sa.String(length=50), nullable=True),
    sa.Column('bankname', sa.String(length=50), nullable=True),
    sa.Column('accountno', sa.String(length=50), nullable=True),
    sa.Column('ifsc', sa.String(length=50), nullable=True),
    sa.Column('transportercode', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('ownerid')
    )
    op.create_table('railwaysiding',
    sa.Column('entryid', sa.Integer(), nullable=False),
    sa.Column('vehicleno', sa.String(length=50), nullable=True),
    sa.Column('grosswb', sa.String(length=50), nullable=True),
    sa.Column('gross', sa.Integer(), nullable=True),
    sa.Column('tarewb', sa.String(length=10), nullable=True),
    sa.Column('tare', sa.Integer(), nullable=True),
    sa.Column('net', sa.Integer(), nullable=True),
    sa.Column('entrytime', sa.DateTime(), nullable=True),
    sa.Column('shortage', sa.Integer(), nullable=True),
    sa.Column('exittime', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.String(length=50), nullable=True),
    sa.Column('vehicleid', sa.Integer(), nullable=True),
    sa.Column('challannet', sa.Integer(), nullable=True),
    sa.Column('challnno', sa.String(length=50), nullable=True),
    sa.Column('slipno', sa.String(length=50), nullable=True),
    sa.Column('grosswbid', sa.Integer(), nullable=True),
    sa.Column('tarewbid', sa.Integer(), nullable=True),
    sa.Column('usergross', sa.String(length=50), nullable=True),
    sa.Column('usertare', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('entryid')
    )
    op.create_table('vehicles',
    sa.Column('vehicleid', sa.Integer(), nullable=False),
    sa.Column('vehicleno', sa.String(length=50), nullable=True),
    sa.Column('compliant', sa.Integer(), nullable=True),
    sa.Column('ownerid', sa.Integer(), nullable=True),
    sa.Column('ownername', sa.String(length=50), nullable=True),
    sa.Column('ownermobile', sa.String(length=50), nullable=True),
    sa.Column('rcno', sa.String(length=50), nullable=True),
    sa.Column('tempno', sa.String(length=50), nullable=True),
    sa.Column('chasisno', sa.String(length=50), nullable=True),
    sa.Column('fitnessexpiry', sa.DateTime(), nullable=True),
    sa.Column('insuranceexpiry', sa.DateTime(), nullable=True),
    sa.Column('permitexpiry', sa.DateTime(), nullable=True),
    sa.Column('pollutionexpiry', sa.DateTime(), nullable=True),
    sa.Column('permittype', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('statuschangedate', sa.DateTime(), nullable=True),
    sa.Column('craetedate', sa.DateTime(), nullable=True),
    sa.Column('ownerpan', sa.String(length=50), nullable=True),
    sa.Column('rfno', sa.String(length=50), nullable=True),
    sa.Column('permit', sa.String(length=50), nullable=True),
    sa.Column('insurance', sa.String(length=50), nullable=True),
    sa.Column('pollution', sa.String(length=50), nullable=True),
    sa.Column('fitness', sa.String(length=50), nullable=True),
    sa.Column('isactive', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('roadtax', sa.String(length=50), nullable=True),
    sa.Column('roadtaxexpiry', sa.DateTime(), nullable=True),
    sa.Column('rcdate', sa.DateTime(), nullable=True),
    sa.Column('wheeler', sa.Integer(), nullable=True),
    sa.Column('vowner', sa.String(length=50), nullable=True),
    sa.Column('vcontact', sa.String(length=50), nullable=True),
    sa.Column('vaddress', sa.String(length=50), nullable=True),
    sa.Column('vownership', sa.Boolean(), server_default='false', nullable=True),
    sa.PrimaryKeyConstraint('vehicleid')
    )
    op.create_table('weightbridge',
    sa.Column('wbid', sa.Integer(), nullable=False),
    sa.Column('wbname', sa.String(length=100), nullable=False),
    sa.Column('locationid', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('wbid'),
    sa.UniqueConstraint('wbid'),
    sa.UniqueConstraint('wbid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weightbridge')
    op.drop_table('vehicles')
    op.drop_table('railwaysiding')
    op.drop_table('owner')
    op.drop_table('locations')
    op.drop_table('ingate')
    op.drop_table('User')
    # ### end Alembic commands ###
