"""empty message

Revision ID: 6a0ba58b459b
Revises: 2c05c4518998
Create Date: 2021-06-23 23:28:18.107080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a0ba58b459b'
down_revision = '2c05c4518998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Outgate', 'tarewbid')
    op.add_column('blacklist_tokens', sa.Column('userid', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('blacklist_tokens', 'user_id')
    op.drop_column('vehicles', 'vownership')
    op.drop_column('vehicles', 'vaddress')
    op.drop_column('vehicles', 'vowner')
    op.drop_column('vehicles', 'vcontact')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('vcontact', sa.VARCHAR(length=50), nullable=True))
    op.add_column('vehicles', sa.Column('vowner', sa.VARCHAR(length=50), nullable=True))
    op.add_column('vehicles', sa.Column('vaddress', sa.VARCHAR(length=50), nullable=True))
    op.add_column('vehicles', sa.Column('vownership', sa.BOOLEAN(), server_default=sa.text("'false'"), nullable=True))
    op.add_column('blacklist_tokens', sa.Column('user_id', sa.INTEGER(), nullable=False))
    op.drop_column('blacklist_tokens', 'userid')
    op.add_column('Outgate', sa.Column('tarewbid', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
